// src/app/layout.tsx
import type { Metadata } from "next";
import { Nunito } from "next/font/google"; // Import Nunito from next/font/google
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/navigation/header";
import Footer from "@/components/navigation/footer";

// Load Nunito font
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"] // Adjust weights as needed
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* Added Header component */}
        {children}
        <Footer /> {/* Added Footer component */}
      </body>
    </html>
  );
}
